version: '2'

services:
  fts_with_pg:
    image: postgres:11.2
    command: ["postgres", "-c", "log_min_duration_statement=1000", "-c", "log_destination=stderr"]
    container_name: fts_with_pg
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./install_extensions.sh:/docker-entrypoint-initdb.d/install_extensions.sh
    - ./data:/data
    ports:
      - 5666:5432